<form action="/application/index/create" method="POST">
    <label for="">Nome</label>
    <input type="text" name="nome">
    <br>
    <label for="">Cep</label>
    <input type="text" name="cep">
    <br>
    <label for="">Endereço</label>
    <input type="text" name="endereco">
    <br>
    <label for="">Numero</label>
    <input type="text" name="numero">
    <br>
    <label for="">Complemento</label>
    <input type="text" name="complemento">
    <br>
    <label for="">Cidade</label>
    <input type="text" name="cidade">
    <br>
    <label for="">Bairro</label>
    <input type="text" name="bairro">
    <br>
    <label for="">Estado</label>
    <input type="text" name="estado">
    <br>
    <label for="">Telefone</label>
    <input type="text" name="telefone">
    <br>
    <label for="">Email</label>
    <input type="text" name="email">
    <br>
    <button type="submit" class="btn btn-success">Enviar</button>
</form>