<a href="/application/index/create">Cadastrar Cliente</a>
<table class="table">
    <thead>
    <tr>
        <th>Nome</th>
        <th>Endereço</th>
        <th>Cidade</th>
        <th>Bairro</th>
        <th>Ação</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->clientes as $o): ?>
        <tr>
            <td><?= $o->getNome(); ?></td>
            <td><?= $o->getEndereco(); ?></td>
            <td><?= $o->getCidade(); ?></td>
            <td><?= $o->getBairro(); ?></td>
            <td>
                <a href="/application/index/edit/<?php echo $o->getId(); ?>">Editar</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>